# Generated by Django 5.1.4 on 2024-12-23 04:11

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload a service icon image', null=True, upload_to=dashboard.models.service_icon_path),
        ),
    ]
