# Generated by Django 5.1.4 on 2024-12-23 06:44

import dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.ImageField(blank=True, help_text='Upload a gallery image', null=True, upload_to=dashboard.models.gallery_image_path)),
                ('image_description', models.CharField(max_length=50)),
                ('image_name', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': "Gallery's",
                'db_table': 'gallery',
                'ordering': ['-created_date'],
            },
        ),
    ]
