# Generated by Django 5.1.4 on 2024-12-23 08:26

import dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_date'], 'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.ImageField(blank=True, help_text='Website Logo', null=True, upload_to=dashboard.models.site_logo_path)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SiteLogo',
                'verbose_name_plural': 'SiteLogos',
                'db_table': 'site_logo',
                'ordering': ['-created_date'],
            },
        ),
    ]
