# Generated by Django 5.1.4 on 2024-12-23 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_gallery_options_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('chosen_option', models.CharField(max_length=25, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('message', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Inquery',
                'verbose_name_plural': 'Inquiries',
                'db_table': 'inquery',
                'ordering': ['-created_date'],
            },
        ),
    ]
