# Generated by Django 5.1.4 on 2024-12-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_inquery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquery',
            old_name='message',
            new_name='job_description',
        ),
        migrations.RemoveField(
            model_name='inquery',
            name='chosen_option',
        ),
        migrations.RemoveField(
            model_name='inquery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inquery',
            name='time',
        ),
        migrations.AddField(
            model_name='inquery',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquery',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquery',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='inquery',
            name='job_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
