# Generated by Django 5.1.4 on 2024-12-24 10:53

import dashboard.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_message_inquery_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('site_logo', models.ImageField(blank=True, help_text='Blog Image', null=True, upload_to=dashboard.models.blog_image_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
