# Generated by Django 5.1.4 on 2024-12-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='site_logo',
            new_name='image',
        ),
    ]
