# Generated by Django 5.1.4 on 2024-12-24 11:40

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_rename_site_logo_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
