# Generated by Django 5.1.4 on 2024-12-24 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_service'),
        ('dashboard', '0009_alter_blog_blog_content'),
    ]

    operations = [
    ]
