# Generated by Django 5.1.4 on 2024-12-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_timezone_alter_service_icon_eventhandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
